// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF81lRmz9v10sSdIb8ko1VOTF3DIJdSLI',
    appId: '1:817244827128:web:9bc681faba684d6cddba0d',
    messagingSenderId: '817244827128',
    projectId: 'flutterfirebase-f7426',
    authDomain: 'flutterfirebase-f7426.firebaseapp.com',
    databaseURL: 'https://flutterfirebase-f7426-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-f7426.firebasestorage.app',
    measurementId: 'G-R45RMTEBFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOi-8MAdW5xwEz-v64mq2vPyG2hVJqAg0',
    appId: '1:817244827128:android:d379d634855c3cabddba0d',
    messagingSenderId: '817244827128',
    projectId: 'flutterfirebase-f7426',
    databaseURL: 'https://flutterfirebase-f7426-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-f7426.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN5jzaUkKO-IoQ6ilvv310wMfaZg_5tZ4',
    appId: '1:817244827128:ios:6b1869e589c9601dddba0d',
    messagingSenderId: '817244827128',
    projectId: 'flutterfirebase-f7426',
    databaseURL: 'https://flutterfirebase-f7426-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-f7426.firebasestorage.app',
    androidClientId: '817244827128-ef4gd9bg3f4538bob3hbvminan89jdr8.apps.googleusercontent.com',
    iosClientId: '817244827128-q6cfqfh5dkn173vp0bb89kngb9i0la3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.olxPrototype',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN5jzaUkKO-IoQ6ilvv310wMfaZg_5tZ4',
    appId: '1:817244827128:ios:6b1869e589c9601dddba0d',
    messagingSenderId: '817244827128',
    projectId: 'flutterfirebase-f7426',
    databaseURL: 'https://flutterfirebase-f7426-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-f7426.firebasestorage.app',
    androidClientId: '817244827128-ef4gd9bg3f4538bob3hbvminan89jdr8.apps.googleusercontent.com',
    iosClientId: '817244827128-q6cfqfh5dkn173vp0bb89kngb9i0la3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.olxPrototype',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF81lRmz9v10sSdIb8ko1VOTF3DIJdSLI',
    appId: '1:817244827128:web:39ad6fd658308f8fddba0d',
    messagingSenderId: '817244827128',
    projectId: 'flutterfirebase-f7426',
    authDomain: 'flutterfirebase-f7426.firebaseapp.com',
    databaseURL: 'https://flutterfirebase-f7426-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-f7426.firebasestorage.app',
    measurementId: 'G-J95N042PTQ',
  );

}